spring:
  application:
    name: ${SERVICE:match-service}
    type: ${MATCH:match}
  data:
    rest:
      basePath: /data
    mongodb:
      database: ${DB:match}
server:
  port: ${PORT:8930}
eureka:
  instance:
    hostname: localhost
    metadataMap:
      zone: zone1
logging:
  level:
    org:
      springframework: info
    hibernate:
      SQL: debug
    com: debug


      